# Generated by Django 4.2.2 on 2025-02-11 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=2048)),
                ('short_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('custom_alias', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.BigIntegerField(default=0)),
                ('unique_visitors', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='URLAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referer', models.URLField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='shortner.url')),
            ],
            options={
                'indexes': [models.Index(fields=['url', 'accessed_at'], name='shortner_ur_url_id_bf5420_idx'), models.Index(fields=['ip_address'], name='shortner_ur_ip_addr_1d57e2_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['short_code'], name='shortner_ur_short_c_600b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='url',
            index=models.Index(fields=['custom_alias'], name='shortner_ur_custom__3f16f4_idx'),
        ),
    ]
